version: "3"

dotenv:
  - ".env"
vars:
  PLUGIN_ID: "typst-mate"

tasks:
  default:
    - task: help

  help:
    silent: true
    cmds:
      - task -l

  check:
    cmds:
      - bun update --latest
      - bunx biome check

  putstatic:
    vars:
      PLUGIN_DIR: "{{.CONFIG_DIR}}/plugins/{{.PLUGIN_ID}}"
      version:
        sh: "bun scripts/version.ts --type mock"
    cmds:
      - touch '{{.PLUGIN_DIR}}/.hotreload'
      - cp manifest.json '{{.PLUGIN_DIR}}'
    desc: "Copy static files to plugin directory"
  wasm:
    vars:
      PLUGIN_DIR: "{{.CONFIG_DIR}}/plugins/{{.PLUGIN_ID}}"
      version:
        sh: "bun scripts/version.ts --type mock"
    cmds:
      - wasm-pack build wasm --target web --dev --out-dir ../pkg
      - rm -f '{{.PLUGIN_DIR}}/'*.wasm
      - mv './pkg/typst_wasm_bg.wasm' '{{.PLUGIN_DIR}}/typst-{{.version}}.wasm'
    desc: "Build WASM file and copy to plugin directory"
  dev:
    cmds:
      - bunx --bun vite build -w -m development --outDir '{{.CONFIG_DIR}}/plugins/{{.PLUGIN_ID}}'
    desc: "Build in development mode and copy to plugin directory"

  symbol:
    cmds:
      - bun scripts/symbols.ts
    desc: "build symbols file"

  release:
    vars:
      tag:
        sh: "bun scripts/version.ts --type {{.TYPE}}"
    cmds:
      - git add manifest.json versions.json
      - git commit -m "release {{.tag}}"
      - git tag "{{.tag}}"
      - git push
      - git push origin "{{.tag}}"
      - task wasm
      - task putstatic
    preconditions:
      - sh: "[ {{.TYPE}} != '' ]"
    desc: "e.g. task release TYPE=major | TYPE=minor | TYPE=patch | TYPE=mock"
